In [13]:
import numpy as np

U = np.array([[0.816,0.577,0.707],[-0.577, 0.816,0.707], [0.816,0.577, 0.707]])
print("U: \n", U)
print()
print("U.T: \n", U.T)
print()
print ("U.dot(U.T): \n", np.round(U.dot(U.T)))

S = np.diag([8.5,2,0.1])
print()
print("S: \n", S)

print()
print ("U.dot(S): \n", U.dot(S))

U: 
 [[ 0.816  0.577  0.707]
 [-0.577  0.816  0.707]
 [ 0.816  0.577  0.707]]

U.T: 
 [[ 0.816 -0.577  0.816]
 [ 0.577  0.816  0.577]
 [ 0.707  0.707  0.707]]

U.dot(U.T): 
 [[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]

S: 
 [[8.5 0.  0. ]
 [0.  2.  0. ]
 [0.  0.  0.1]]

U.dot(S): 
 [[ 6.936   1.154   0.0707]
 [-4.9045  1.632   0.0707]
 [ 6.936   1.154   0.0707]]


#### Demo Eigen

In [14]:
import numpy as np
from numpy.linalg import eig, inv
from numpy import diag

In [16]:
A = np.array([[1, 2], [2, 3]])

In [17]:
values, vectors = eig(A)

In [19]:
print("Values: ", values)
print("Vectors: ", vectors)

Values:  [-0.23606798  4.23606798]
Vectors:  [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [20]:
Q = vectors
Q

array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]])

In [21]:
print(Q@Q.T)

[[1. 0.]
 [0. 1.]]
